### ISSUE TITLE
java.lang.module.FindException: Automatic-Module-Name: org.xmlunit.xmlunit-core: Invalid module name: 'xmlunit-core' is not a Java identifier

### ISSUE THREAD

**Issue by tzieleniewski** [xmlunit/xmlunit#136]
I was investingating project with jdeps tool and encountered automatic module name problem related to xmlunit dependecy.

**Environment**
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Jdeps stack trace**
```
> jdeps --module-path target/dependency target/app.jar
Exception in thread "main" java.lang.module.FindException: Unable to derive module descriptor for target\dependency\xmlunit-core-2.6.0.jar
        at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:648)
        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:331)
        at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:284)
        at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:232)
        at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
        at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:166)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:558)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:589)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:543)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:519)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: java.lang.module.FindException: Automatic-Module-Name: org.xmlunit.xmlunit-core: Invalid module name: 'xmlunit-core' is not a Java identifier
        at java.base/jdk.internal.module.ModulePath.deriveModuleDescriptor(ModulePath.java:505)
        at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:644)
        ... 10 more
```

**Comment by bodewig** [comment]
Actually, this affects all our "modules".

The value of the manifest entry is defined inside the parent POM and we need to use some other kind of property than `project.artifactId` to build the name. Replacing the `-` with a `_` (likely manually) would do the trick.

**Comment by bodewig** [comment]
Thanks, I have read that in the past but simply overlooked the fact that all our artifact names contain dashes.

The issue is pretty trivial to fix, I'm deliberately keeping it open for a while as it provides  chance for somebody new to get their feet wet.

Re-reading Stephen's post xmlunit-core should probably use `org.xmlunit`, the legacy module `org.custommonkey.xmlunit`, and all the other modules can use the name of their base package. A not quite so trivial case is the "sumo" jar provided by the legacy module, it is probably best to not provide any `Automatic-Module-Name` at all here.

**Comment by bodewig** [comment]
2.6.2 has just been released
