### ISSUE TITLE
Does xmlunit 2.10 work with java 21?

### ISSUE THREAD

**Issue by d-miller-1** [xmlunit/xmlunit#267]
I ask because we are getting this error message

```
org.custommonkey.xmlunit.exceptions.ConfigurationException: class org.custommonkey.xmlunit.jaxp13.Jaxp13XpathEngine cannot access class com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xpath.internal.jaxp to unnamed module @311bf055
	at app//org.custommonkey.xmlunit.jaxp13.Jaxp13XpathEngine.<init>(Jaxp13XpathEngine.java:83)
	at app//org.custommonkey.xmlunit.XMLUnit.newXpathEngine(XMLUnit.java:670)
	at app//org.custommonkey.xmlunit.XMLAssert.assertXpathEvaluatesTo(XMLAssert.java:910)
	at app//org.custommonkey.xmlunit.XMLAssert.assertXpathEvaluatesTo(XMLAssert.java:895)
```
....
```
Caused by: java.lang.IllegalAccessException: class org.custommonkey.xmlunit.jaxp13.Jaxp13XpathEngine cannot access class com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xpath.internal.jaxp to unnamed module @311bf055
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:495)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
	at java.base/java.lang.Class.newInstance(Class.java:725)
	at org.custommonkey.xmlunit.jaxp13.Jaxp13XpathEngine.<init>(Jaxp13XpathEngine.java:75)
	... 44 more
```
and I dont know how to fix it.
The same code works with java 11

**Comment by bodewig** [comment]
Are you setting `XMLUnit,setXPathEngine` explicitly? If so, try setting it to `null` instead.

**Comment by d-miller-1** [comment]
We weren't setting xPathFactory, but explicitly setting it to null seems to have done the trick!
Thanks for your help

**Comment by bodewig** [comment]
hmm, the default value is "null". This is strange. Anyway, I'm glad it helped in your case.
