### ISSUE TITLE
Junit test clean up

### ISSUE THREAD

**Issue by hiufung-kwok** [xmlunit/xmlunit#270]
By running maven clean install, Junit failed on the core module, log attached below:

```
[ERROR] shouldSuccessfullyValidateInstanceWithoutSchemaSource(org.xmlunit.validation.JAXPValidatorTest)  Time elapsed: 0.005 s  <<< ERROR!
org.xmlunit.XMLUnitException: /Users/hiuf/git/dev/java-lib/xmlunit/xmlunit-core/../test-resources/BookXsdGeneratedWithFixedSchemaLocation.xml (No such file or directory)
        at org.xmlunit.validation.JAXPValidatorTest.shouldSuccessfullyValidateInstanceWithoutSchemaSource(JAXPValidatorTest.java:89)
Caused by: java.io.FileNotFoundException: /Users/hiuf/git/dev/java-lib/xmlunit/xmlunit-core/../test-resources/BookXsdGeneratedWithFixedSchemaLocation.xml (No such file or directory)
        at org.xmlunit.validation.JAXPValidatorTest.shouldSuccessfullyValidateInstanceWithoutSchemaSource(JAXPValidatorTest.java:89)

......
tXPathEngineTest.readSource:46 » FileNotFound /User...
[ERROR]   JAXPXPathEngineTest>AbstractXPathEngineTest.readSource:46 » FileNotFound /User...
[ERROR]   JAXPXPathEngineTest>AbstractXPathEngineTest.readSource:46 » FileNotFound /User...
[ERROR]   JAXPXPathEngineTest>AbstractXPathEngineTest.readSource:46 » FileNotFound /User...
[ERROR]   JAXPXPathEngineTest>AbstractXPathEngineTest.readSource:46 » FileNotFound /User...
[INFO] 
[ERROR] Tests run: 420, Failures: 1, Errors: 72, Skipped: 0
[INFO] 

```

And by analysing the log, it seems some of the test case is referencing resource file which is no longer exist (Ex: `BookXsdGeneratedWithFixedSchemaLocation.xml`)
Also I think this go against the best practice by placing the test resource out of the module (Ex: xmlunit-core module Junit test is referencing test resources from the parent module).

Hence I think that make more sense to:
1. Move all test-resource files into its respective module 
2. Do a clean up on existing the Junit, remove invalid test-cases or test relying on .xsd that no longer exist.

**Comment by hiufung-kwok** [comment]
Also by doing so, we can also elminate the hard coded relative path:
```
public static final String TEST_RESOURCE_DIR = "../../../test-resources/";
```

**Comment by hiufung-kwok** [comment]
NVM, I realised the test-resource folder is under git-submodule :)
