### ISSUE TITLE
CompareMatcher throws NPE when used in combination with other matcher, and the other matcher does not match

### ISSUE THREAD

**Issue by simin-xia** [xmlunit/xmlunit#81]
A simple JUnit Test:

  ` assertThat("not empty", both(Matchers.isEmptyString()).and(CompareMatcher.isIdenticalTo("")));`

And this throws an NPE:

java.lang.NullPointerException
	at org.xmlunit.matchers.CompareMatcher.firstComparison(CompareMatcher.java:336)
	at org.xmlunit.matchers.CompareMatcher.describeTo(CompareMatcher.java:307)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.BaseDescription.appendList(BaseDescription.java:94)
	at org.hamcrest.BaseDescription.appendList(BaseDescription.java:85)
	at org.hamcrest.core.AllOf.describeTo(AllOf.java:38)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.core.CombinableMatcher.describeTo(CombinableMatcher.java:25)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:14)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)

**Comment by bodewig** [comment]
Thanks for reporting this, it also applies to the validation matcher.

**Comment by bodewig** [comment]
I'll need to check whether the same applies to the constraints in XMLUnit.NET as well. After that 2.1.1 (either just for Java or for both) should get released in the coming days.

**Comment by bodewig** [comment]
I've released 2.1.1.
