### ISSUE TITLE
Only one evaluation possible when Source is created by Input#fromString

### ISSUE THREAD

**Issue by PascalSchumacher** [xmlunit/xmlunit#84]
This test:

```java
@Test
public void test() {
    Source xml = Input.fromString("<a><b>bvalue</b><c>cvalue</c></a>").build();
    
    JAXPXPathEngine xpath = new JAXPXPathEngine();
    
    Assert.assertEquals(xpath.evaluate("//a/b", xml), "bvalue");
    Assert.assertEquals(xpath.evaluate("//a/c", xml), "cvalue");
}
```

fails with

>org.xmlunit.XMLUnitException
	at org.xmlunit.xpath.JAXPXPathEngine.evaluate(JAXPXPathEngine.java:72)
	at com.tses.outcore.scaffolding.Tester.test(Tester.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.xml.xpath.XPathExpressionException
	at org.apache.xpath.jaxp.XPathImpl.evaluate(XPathImpl.java:481)
	at org.apache.xpath.jaxp.XPathImpl.evaluate(XPathImpl.java:521)
	at org.xmlunit.xpath.JAXPXPathEngine.evaluate(JAXPXPathEngine.java:70)
	... 24 more
Caused by: java.io.IOException: Stream closed
	at java.io.StringReader.ensureOpen(StringReader.java:56)
	at java.io.StringReader.read(StringReader.java:90)
	at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.skipString(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.apache.xpath.jaxp.XPathImpl.evaluate(XPathImpl.java:474)
	... 26 more

It works for `Input#fromFile` and `Input#fromJaxb`.

**Comment by bodewig** [comment]
This is because it uses `StreamSource` under the covers - as does `fromByteArray`. I've changed the code to now return fresh streams/readers whenever the source is used.

Many thanks for the report.

**Comment by PascalSchumacher** [comment]
Thanks for the fix. :) And many thanks for all your excellent work on xml-unit. :+1:

**Comment by bodewig** [comment]
The same issue has been present in XMLUnit.NET as well, thanks again.

**Comment by bodewig** [comment]
XMLUnit 2.2.0 which contains the fix has been released yesterday, I just didn't find the time to announce it before today.

**Comment by PascalSchumacher** [comment]
Thank. :+1:  Will update to 2.2.0 tomorrow. :smile:
